(()=>{'use strict';
const KEY='librarium_v2_next';
const ALIAS={conspiracao:['conspiracy','conspiracy theories'],historia:['history'],filosofia:['philosophy'],arqueologia:['archaeology'],mitologia:['mythology'],musica:['music'],ciencia:['science'],psicologia:['psychology'],biografia:['biography'],religiao:['religion'],astronomia:['astronomy']};
let st={view:'home',books:[],q:'',author:'',year:'',lang:'Todos',sort:'relevancia',status:'',sel:null,tab:'resumo',lib:[],lists:[],recent:[]};
try{Object.assign(st,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])), norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(), clean=s=>String(s||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const lang=x=>({pt:'Português',por:'Português',en:'Inglês',eng:'Inglês',es:'Espanhol',spa:'Espanhol',fr:'Francês',fre:'Francês',de:'Alemão',ger:'Alemão',it:'Italiano',ita:'Italiano'})[(x||'').toLowerCase()]||(x||'Não indicada').toUpperCase();
function persist(){localStorage.setItem(KEY,JSON.stringify({lib:st.lib,lists:st.lists,recent:st.recent}))}
function key(b){return norm(b.title+'|'+(b.authors?.[0]||''))}
function isbn(v){let a=v.industryIdentifiers||[],x=a.find(i=>i.type==='ISBN_13')||a[0];return x?.identifier||''}
function cover(v){let x=v.imageLinks||{};return String(x.extraLarge||x.large||x.medium||x.small||x.thumbnail||x.smallThumbnail||'').replace('http:','https:')}
function gb(x){let v=x.volumeInfo||{},p=x.saleInfo?.retailPrice;return{id:'g'+x.id,title:v.title||'',subtitle:v.subtitle||'',authors:v.authors||[],year:(v.publishedDate||'').slice(0,4),date:v.publishedDate||'',publisher:v.publisher||'',pages:v.pageCount||'',language:v.language||'',isbn:isbn(v),description:clean(v.description),rating:v.averageRating||'',count:v.ratingsCount||'',cover:cover(v),subjects:v.categories||[],source:'Google Books',preview:v.previewLink||'',info:v.infoLink||'',price:p?.amount||'',currency:p?.currencyCode||'',editions:[],related:[],pt:''}}
function ob(d){return{id:'o'+(d.key||Math.random()),title:d.title||'',subtitle:d.subtitle||'',authors:d.author_name||[],year:d.first_publish_year?String(d.first_publish_year):'',date:String(d.first_publish_year||''),publisher:d.publisher?.[0]||'',pages:d.number_of_pages_median||'',language:d.language?.[0]||'',isbn:d.isbn?.[0]||'',description:clean(d.first_sentence?.[0]),rating:'',count:'',cover:d.cover_i?'https://covers.openlibrary.org/b/id/'+d.cover_i+'-L.jpg?default=false':'',subjects:(d.subject||[]).slice(0,10),source:'Open Library',preview:'',info:d.key?'https://openlibrary.org'+d.key:'',price:'',currency:'',editions:[],related:[],pt:''}}
function score(b){return(b.cover?5:0)+(b.authors.length?3:0)+(b.description.length>120?4:b.description?2:0)+(b.isbn?2:0)+(b.publisher?1:0)+(b.pages?1:0)+(b.rating?2:0)}
function merge(a,b){let A=score(a)>=score(b)?a:b,B=A===a?b:a;return Object.assign({},A,{subtitle:A.subtitle||B.subtitle,authors:A.authors.length?A.authors:B.authors,year:A.year||B.year,date:A.date||B.date,publisher:A.publisher||B.publisher,pages:A.pages||B.pages,language:A.language||B.language,isbn:A.isbn||B.isbn,description:A.description.length>=B.description.length?A.description:B.description,rating:A.rating||B.rating,count:A.count||B.count,cover:A.cover||B.cover,subjects:A.subjects.length?A.subjects:B.subjects,source:A.source===B.source?A.source:'Google + Open Library',preview:A.preview||B.preview,info:A.info||B.info,price:A.price||B.price,currency:A.currency||B.currency})}
async function google(q,l=''){let u='https://www.googleapis.com/books/v1/volumes?q='+encodeURIComponent(q)+'&maxResults=40&printType=books'+(l?'&langRestrict='+l:'');let r=await fetch(u);if(!r.ok)throw Error('Google');let j=await r.json();return(j.items||[]).map(gb)}
async function openlib(q){let r=await fetch('https://openlibrary.org/search.json?q='+encodeURIComponent(q)+'&limit=50');if(!r.ok)throw Error('OL');let j=await r.json();return(j.docs||[]).map(ob)}
async function tr(t){t=clean(t);if(!t)return'';if(/\b(que|para|com|uma|não|livro|história|este|esta|sobre|mais)\b/i.test(t))return t;try{let r=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=pt&dt=t&q='+encodeURIComponent(t.slice(0,4500)));if(!r.ok)return t;let j=await r.json();return clean((j[0]||[]).map(x=>x?.[0]||'').join(''))||t}catch(e){return t}}
function money(b){if(!b.price)return'';try{return new Intl.NumberFormat('pt-PT',{style:'currency',currency:b.currency||'EUR'}).format(b.price)}catch(e){return b.price}}
function saved(b){return st.lib.some(x=>x.key===key(b))}
function libraryItem(b){let old=st.lib.find(x=>x.key===key(b));return old||{key:key(b),title:b.title,authors:b.authors,cover:b.cover,year:b.year,status:'Quero ler',rating:0,progress:0,notes:'',quotes:[],isbn:b.isbn}}
function add(b,status){let item=libraryItem(b),i=st.lib.findIndex(x=>x.key===item.key);item=Object.assign({},item,{title:b.title,authors:b.authors,cover:b.cover,year:b.year,isbn:b.isbn,status:status||item.status});i>=0?st.lib[i]=item:st.lib.unshift(item);persist();render()}
function updateLib(k,f,v){let x=st.lib.find(i=>i.key===k);if(x)x[f]=v;persist();render()}
function removeLib(k){st.lib=st.lib.filter(x=>x.key!==k);st.lists.forEach(l=>l.items=l.items.filter(i=>i!==k));persist();render()}
function cov(b,small=false){return b.cover?'<img loading="lazy" src="'+esc(b.cover)+'">':'<div class="cover-fallback '+(small?'small':'')+'"><b>'+esc((b.title||'Livro').slice(0,34))+'</b><span>'+esc((b.authors||[]).join(', '))+'</span></div>'}
function nav(){let tabs=[['home','Início'],['discover','Descobrir'],['library','Biblioteca'],['lists','Listas']];return '<header class="topbar"><div class="topbar-inner"><button class="brand" data-nav="home">Librarium<small>BIBLIOTECA PESSOAL</small></button><nav class="nav">'+tabs.map(x=>'<button data-nav="'+x[0]+'" class="'+(st.view===x[0]?'active':'')+'">'+x[1]+(x[0]==='library'?'<span class="count">'+st.lib.length+'</span>':'')+'</button>').join('')+'</nav></div></header>'}
function card(b,i,source='books'){return '<article class="book-card" data-open="'+i+'" data-source="'+source+'"><div class="cover">'+cov(b)+'<button class="save-fab '+(saved(b)?'saved':'')+'" data-save="'+i+'" data-source="'+source+'">'+(saved(b)?'✓':'＋')+'</button></div><div class="book-info"><h3>'+esc(b.title)+'</h3><div class="author">'+esc((b.authors||[]).join(', '))+'</div><div class="meta"><span>'+esc(b.year||'—')+'</span><span>'+(b.rating?'★ '+esc(b.rating):money(b)||lang(b.language))+'</span></div>'+(b.description?'<p class="snippet">'+esc(b.description)+'</p>':'')+'</div></article>'}
function searchBox(){return '<section class="search-panel"><div class="search-main"><input id="q" class="field" placeholder="Título, autor, assunto ou ISBN" value="'+esc(st.q)+'"><input id="author" class="field" placeholder="Autor" value="'+esc(st.author)+'"><button id="search" class="primary">Pesquisar</button></div><div class="filters"><input id="year" class="field" placeholder="Ano" value="'+esc(st.year)+'"><select id="lang" class="select"><option>Todos</option><option value="pt" '+(st.lang==='pt'?'selected':'')+'>Português</option><option value="en" '+(st.lang==='en'?'selected':'')+'>Inglês</option></select><select id="sort" class="select"><option value="relevancia">Relevância</option><option value="avaliacao" '+(st.sort==='avaliacao'?'selected':'')+'>Melhor avaliados</option><option value="recentes" '+(st.sort==='recentes'?'selected':'')+'>Mais recentes</option></select><select id="quality" class="select"><option value="all">Todos</option><option value="cover">Com capa</option><option value="desc">Com descrição</option></select></div></section>'}
function home(){let reading=st.lib.filter(x=>x.status==='A ler').slice(0,4), recent=st.recent.slice(0,6);return '<main class="content"><section class="hero home-hero"><div><div class="eyebrow">DESCOBRIR · COMPARAR · GUARDAR</div><h1>Uma biblioteca que começa antes da leitura.</h1><p>Pesquisa livros, compara edições, organiza leituras, guarda notas e acompanha o teu progresso.</p><button class="primary hero-btn" data-nav="discover">Explorar livros</button></div><aside class="dashboard-card"><div><b>'+st.lib.length+'</b><span>na biblioteca</span></div><div><b>'+st.lib.filter(x=>x.status==='Li').length+'</b><span>lidos</span></div><div><b>'+st.lists.length+'</b><span>listas</span></div></aside></section><section class="home-grid"><div class="feature"><span>01</span><h3>Escolher melhor</h3><p>Capas, descrições, edições, avaliações e lojas reunidas numa única ficha.</p></div><div class="feature"><span>02</span><h3>Ler com contexto</h3><p>Assuntos, obras relacionadas, notas pessoais e citações ficam ligadas ao livro.</p></div><div class="feature"><span>03</span><h3>Construir uma biblioteca</h3><p>Estados de leitura, progresso, favoritos e listas temáticas persistem neste aparelho.</p></div></section>'+(reading.length?'<section><div class="section-head"><div><h2>A ler agora</h2><p>Continua de onde ficaste.</p></div></div><div class="reading-row">'+reading.map(x=>'<article class="reading-card">'+(x.cover?'<img src="'+esc(x.cover)+'">':'')+'<div><h3>'+esc(x.title)+'</h3><p>'+esc(x.authors.join(', '))+'</p><div class="progress"><span style="width:'+Math.max(0,Math.min(100,+x.progress||0))+'%"></span></div><small>'+ (+x.progress||0)+'% concluído</small></div></article>').join('')+'</div></section>':'')+(recent.length?'<section><div class="section-head"><div><h2>Vistos recentemente</h2><p>Livros que abriste nesta sessão.</p></div></div><div class="mini-grid">'+recent.map((b,i)=>'<button class="mini-book" data-open-recent="'+i+'">'+cov(b,true)+'<span>'+esc(b.title)+'</span></button>').join('')+'</div></section>':'')+'<section><div class="section-head"><div><h2>Explorar por ideias</h2><p>Atalhos para começar uma pesquisa.</p></div></div><div class="topic-cloud">'+['História','Filosofia','Ciência','Música','Arqueologia','Mitologia','Psicologia','Biografia','Astronomia','Religião'].map(t=>'<button class="topic" data-topic="'+t+'">'+t+'</button>').join('')+'</div></section></main>'}
function discover(){return '<main class="content"><div class="page-head"><div><div class="eyebrow">CATÁLOGO</div><h1>Descobrir livros</h1><p>Pesquisa por título, autor, assunto ou ISBN e filtra os resultados.</p></div></div>'+searchBox()+'<div class="section-head"><div><h2>Resultados</h2><p>'+esc(st.status||'Começa por fazer uma pesquisa.')+'</p></div></div>'+(st.books.length?'<div class="book-grid">'+st.books.map((b,i)=>card(b,i)).join('')+'</div>':'<div class="empty">A pesquisa ainda está vazia.</div>')+'</main>'}
function library(){let f=st.filter||'Todos',states=['Todos','Quero ler','A ler','Li','Tenho','Favorito'],B=f==='Todos'?st.lib:st.lib.filter(x=>x.status===f);return '<main class="content"><div class="page-head"><div><div class="eyebrow">COLECÇÃO</div><h1>A minha biblioteca</h1><p>Organiza leituras, progresso e avaliação pessoal.</p></div></div><div class="stat-grid"><div class="stat"><b>'+st.lib.length+'</b><span>Total</span></div><div class="stat"><b>'+st.lib.filter(x=>x.status==='A ler').length+'</b><span>A ler</span></div><div class="stat"><b>'+st.lib.filter(x=>x.status==='Li').length+'</b><span>Lidos</span></div><div class="stat"><b>'+st.lib.filter(x=>x.status==='Favorito').length+'</b><span>Favoritos</span></div></div><div class="layout-two"><aside class="side-nav">'+states.map(s=>'<button data-filter="'+s+'" class="'+(f===s?'active':'')+'">'+s+'</button>').join('')+'</aside><section>'+(B.length?'<div class="library-grid">'+B.map(x=>'<article class="library-card">'+(x.cover?'<img src="'+esc(x.cover)+'">':'<div class="cover-fallback"><b>'+esc(x.title)+'</b></div>')+'<div><h3>'+esc(x.title)+'</h3><p>'+esc(x.authors.join(', '))+' · '+esc(x.year||'—')+'</p><div class="form-grid"><select class="select" data-status="'+esc(x.key)+'">'+states.slice(1).map(s=>'<option '+(x.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select><select class="select" data-rating="'+esc(x.key)+'"><option value="0">Sem nota</option>'+[1,2,3,4,5].map(n=>'<option value="'+n+'" '+(+x.rating===n?'selected':'')+'>'+n+'/5</option>').join('')+'</select></div><label class="progress-label">Progresso <input type="range" min="0" max="100" value="'+(+x.progress||0)+'" data-progress="'+esc(x.key)+'"><span>'+ (+x.progress||0)+'%</span></label><textarea class="notes" data-notes="'+esc(x.key)+'" placeholder="Notas pessoais">'+esc(x.notes||'')+'</textarea><div class="row-actions"><button class="ghost" data-list-add="'+esc(x.key)+'">Adicionar a lista</button><button class="ghost danger" data-remove="'+esc(x.key)+'">Retirar</button></div></div></article>').join('')+'</div>':'<div class="empty">Não há livros nesta secção.</div>')+'</section></div></main>'}
function lists(){return '<main class="content"><div class="page-head"><div><div class="eyebrow">LISTAS</div><h1>Listas pessoais</h1><p>Cria colecções temáticas sem alterar o estado de leitura.</p></div><button id="newList" class="primary">Nova lista</button></div>'+(st.lists.length?'<div class="list-grid">'+st.lists.map((l,i)=>'<section class="list-card"><div class="list-head"><div><h3>'+esc(l.name)+'</h3><p>'+l.items.length+' livros</p></div><button class="ghost danger" data-del-list="'+i+'">Eliminar</button></div><div class="list-books">'+l.items.map(k=>{let x=st.lib.find(b=>b.key===k);return x?'<div class="list-book">'+(x.cover?'<img src="'+esc(x.cover)+'">':'')+'<span>'+esc(x.title)+'</span></div>':''}).join('')+'</div></section>').join('')+'</div>':'<div class="empty">Ainda não criaste listas.</div>')+'</main>'}
async function search(){st.q=$('q').value.trim();st.author=$('author').value.trim();st.year=$('year').value.trim();st.lang=$('lang').value;st.sort=$('sort').value;if(!st.q&&!st.author){st.status='Escreve um título, autor, assunto ou ISBN.';render();return}st.status='A procurar e a cruzar edições…';render();let terms=[st.q],n=norm(st.q);if(ALIAS[n])terms.push(...ALIAS[n]);let jobs=[];terms.forEach(t=>{let q=[t,st.author?'inauthor:'+st.author:''].filter(Boolean).join(' ');jobs.push(google(q,st.lang==='Todos'?'':st.lang),openlib([t,st.author].filter(Boolean).join(' ')));if(st.lang==='Todos')jobs.push(google(q,'pt'))});let rs=await Promise.allSettled(jobs),all=[];rs.forEach(r=>r.status==='fulfilled'&&all.push(...r.value));let m=new Map();all.forEach(b=>{if(!b.title||!b.authors.length)return;let z=key(b);m.set(z,m.has(z)?merge(m.get(z),b):b)});let B=[...m.values()];if(st.year)B=B.filter(b=>b.year===st.year);let ql=$('quality')?.value||'all';if(ql==='cover')B=B.filter(b=>b.cover);if(ql==='desc')B=B.filter(b=>b.description.length>50);if(st.sort==='avaliacao')B.sort((a,b)=>(+b.rating||0)-(+a.rating||0));else if(st.sort==='recentes')B.sort((a,b)=>(+b.year||0)-(+a.year||0));else B.sort((a,b)=>score(b)-score(a));st.books=B.slice(0,72);st.status=st.books.length?st.books.length+' resultados encontrados.':'Sem resultados.';render()}
async function enrich(b){let candidates=[b.description||''], editions=[], related=[];let q='intitle:'+b.title+(b.authors[0]?' inauthor:'+b.authors[0]:'');try{let arr=await google(q,'');arr.forEach(x=>{if(x.description)candidates.push(x.description);editions.push(x)});related=arr.filter(x=>key(x)!==key(b)).slice(0,8)}catch(e){}try{let r=await fetch('https://openlibrary.org/search.json?title='+encodeURIComponent(b.title)+(b.authors[0]?'&author='+encodeURIComponent(b.authors[0]):'')+'&limit=15');if(r.ok){let j=await r.json();(j.docs||[]).forEach(d=>editions.push(ob(d)))}}catch(e){}candidates=candidates.filter(Boolean).sort((a,b)=>b.length-a.length);b.description=candidates[0]||'';b.pt=await tr(b.description);b.editions=dedupe(editions).slice(0,12);b.related=dedupe(related).slice(0,8);return b}
function dedupe(a){let m=new Map();a.forEach(x=>{let z=[norm(x.title),x.isbn||x.year,x.publisher].join('|');if(!m.has(z))m.set(z,x)});return [...m.values()]}
async function openBook(b){st.sel=Object.assign({},b);st.tab='resumo';let r={title:b.title,authors:b.authors,cover:b.cover,year:b.year,isbn:b.isbn};st.recent=[r,...st.recent.filter(x=>key(x)!==key(r))].slice(0,12);persist();render();await enrich(st.sel);render()}
function modal(b){let item=libraryItem(b), tabs=[['resumo','Resumo'],['edicoes','Edições'],['relacionados','Relacionados'],['lojas','Onde comprar'],['notas','Notas']];return '<div class="overlay" id="overlay"><section class="modal"><button id="closeModal" class="close">×</button><div class="book-hero">'+cov(b)+'<div><div class="eyebrow">'+esc(b.source)+'</div><h1>'+esc(b.title)+'</h1>'+(b.subtitle?'<h2>'+esc(b.subtitle)+'</h2>':'')+'<p class="author-big">'+esc(b.authors.join(', '))+'</p><div class="facts"><span>'+esc(b.year||'Ano desconhecido')+'</span><span>'+esc(b.pages||'—')+' págs.</span><span>'+esc(lang(b.language))+'</span><span>'+(b.rating?'★ '+esc(b.rating)+(b.count?' · '+esc(b.count)+' avaliações':''):'Sem avaliação')+'</span></div><div class="actions"><button class="primary" id="saveModal">'+(saved(b)?'Na biblioteca':'Guardar na biblioteca')+'</button><select id="modalStatus" class="select">'+['Quero ler','A ler','Li','Tenho','Favorito'].map(s=>'<option '+(item.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select></div></div></div><div class="modal-tabs">'+tabs.map(t=>'<button data-tab="'+t[0]+'" class="'+(st.tab===t[0]?'active':'')+'">'+t[1]+'</button>').join('')+'</div><div class="modal-body">'+modalTab(b,item)+'</div></section></div>'}
function modalTab(b,item){if(st.tab==='resumo')return '<div class="two-col"><section><h3>Resumo / descrição</h3><div class="desc">'+esc(b.pt||b.description||'Ainda não foi encontrada uma descrição suficientemente completa para esta obra.')+'</div>'+(b.description&&!b.pt?'<p class="loading">A preparar versão portuguesa…</p>':'')+'<h3>Assuntos</h3><div class="tags">'+(b.subjects||[]).slice(0,12).map(s=>'<span>'+esc(s)+'</span>').join('')+'</div></section><aside class="fact-panel"><h3>Ficha</h3><dl><dt>Editora</dt><dd>'+esc(b.publisher||'Não indicada')+'</dd><dt>Data</dt><dd>'+esc(b.date||b.year||'Não indicada')+'</dd><dt>ISBN</dt><dd>'+esc(b.isbn||'Não indicado')+'</dd><dt>Idioma</dt><dd>'+esc(lang(b.language))+'</dd></dl></aside></div>';
if(st.tab==='edicoes')return '<h3>Edições encontradas</h3>'+(b.editions?.length?'<div class="edition-grid">'+b.editions.map(e=>'<article class="edition-card">'+cov(e,true)+'<div><h4>'+esc(e.title)+'</h4><p>'+esc(e.publisher||'Editora não indicada')+' · '+esc(e.year||'—')+'</p><p>'+esc(lang(e.language))+(e.isbn?' · ISBN '+esc(e.isbn):'')+'</p></div></article>').join('')+'</div>':'<p class="muted">A procurar edições…</p>');
if(st.tab==='relacionados')return '<h3>Livros relacionados</h3>'+(b.related?.length?'<div class="related-grid">'+b.related.map((r,i)=>'<button class="related-card" data-related="'+i+'">'+cov(r,true)+'<span>'+esc(r.title)+'</span><small>'+esc(r.authors.join(', '))+'</small></button>').join('')+'</div>':'<p class="muted">A procurar livros relacionados…</p>');
if(st.tab==='lojas'){let q=encodeURIComponent(b.title+' '+(b.isbn||b.authors[0]||''));return '<h3>Onde procurar esta edição</h3><div class="store-grid"><a target="_blank" href="https://www.wook.pt/pesquisa/'+q+'"><b>Wook</b><span>Pesquisar ↗</span></a><a target="_blank" href="https://www.bertrand.pt/pesquisa/'+q+'"><b>Bertrand</b><span>Pesquisar ↗</span></a><a target="_blank" href="https://www.fnac.pt/SearchResult/ResultList.aspx?Search='+q+'"><b>FNAC</b><span>Pesquisar ↗</span></a><a target="_blank" href="https://www.amazon.es/s?k='+q+'"><b>Amazon ES</b><span>Pesquisar ↗</span></a></div><p class="note">O preço mostrado pelas fontes pode não corresponder à edição portuguesa. Histórico e comparação automática de preços exigem um servidor próprio.</p>'}
return '<h3>Notas pessoais</h3><textarea id="modalNotes" class="notes big" placeholder="Ideias, impressões, referências…">'+esc(item.notes||'')+'</textarea><h3>Citações</h3><div id="quoteList">'+(item.quotes||[]).map((q,i)=>'<blockquote>'+esc(q)+'<button data-del-quote="'+i+'">×</button></blockquote>').join('')+'</div><div class="quote-add"><input id="newQuote" class="field" placeholder="Guardar uma citação"><button id="addQuote" class="secondary">Adicionar</button></div><label class="progress-label">Progresso <input id="modalProgress" type="range" min="0" max="100" value="'+(+item.progress||0)+'"><span>'+ (+item.progress||0)+'%</span></label>'}
}
function render(){document.getElementById('app').innerHTML=nav()+(st.view==='home'?home():st.view==='discover'?discover():st.view==='library'?library():lists())+(st.sel?modal(st.sel):'');bind()}
function sourceBook(i,s){return s==='recent'?st.recent[i]:st.books[i]}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{st.view=b.dataset.nav;st.sel=null;render()});if($('search'))$('search').onclick=search;['q','author','year'].forEach(id=>{let e=$(id);if(e)e.onkeydown=x=>x.key==='Enter'&&search()});document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{st.view='discover';st.q=b.dataset.topic;render();setTimeout(search,0)});document.querySelectorAll('[data-open]').forEach(e=>e.onclick=x=>{if(!x.target.closest('[data-save]'))openBook(st.books[+e.dataset.open])});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=x=>{x.stopPropagation();add(st.books[+b.dataset.save])});document.querySelectorAll('[data-open-recent]').forEach(b=>b.onclick=()=>openBook(st.recent[+b.dataset.openRecent]));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{st.filter=b.dataset.filter;render()});document.querySelectorAll('[data-status]').forEach(e=>e.onchange=()=>updateLib(e.dataset.status,'status',e.value));document.querySelectorAll('[data-rating]').forEach(e=>e.onchange=()=>updateLib(e.dataset.rating,'rating',+e.value));document.querySelectorAll('[data-progress]').forEach(e=>e.oninput=()=>{let x=st.lib.find(i=>i.key===e.dataset.progress);if(x){x.progress=+e.value;e.nextElementSibling.textContent=e.value+'%';persist()}});document.querySelectorAll('[data-notes]').forEach(e=>e.onchange=()=>updateLib(e.dataset.notes,'notes',e.value));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeLib(b.dataset.remove));document.querySelectorAll('[data-list-add]').forEach(b=>b.onclick=()=>addToListPrompt(b.dataset.listAdd));if($('newList'))$('newList').onclick=createList;document.querySelectorAll('[data-del-list]').forEach(b=>b.onclick=()=>{st.lists.splice(+b.dataset.delList,1);persist();render()});bindModal()}
function createList(){let n=prompt('Nome da nova lista:');if(n&&n.trim()){st.lists.push({name:n.trim(),items:[]});persist();render()}}
function addToListPrompt(k){if(!st.lists.length){let n=prompt('Ainda não tens listas. Nome da nova lista:');if(!n||!n.trim())return;st.lists.push({name:n.trim(),items:[]})}let names=st.lists.map((l,i)=>(i+1)+'. '+l.name).join('\n'),ans=prompt('Escolhe o número da lista:\n'+names),idx=+ans-1;if(st.lists[idx]&&!st.lists[idx].items.includes(k))st.lists[idx].items.push(k);persist();render()}
function bindModal(){if(!$('closeModal'))return;$('closeModal').onclick=()=>{st.sel=null;render()};$('overlay').onclick=e=>{if(e.target.id==='overlay'){st.sel=null;render()}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{st.tab=b.dataset.tab;render()});$('saveModal').onclick=()=>add(st.sel,$('modalStatus').value);$('modalStatus').onchange=()=>{add(st.sel,$('modalStatus').value)};document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>openBook(st.sel.related[+b.dataset.related]));if($('modalNotes'))$('modalNotes').onchange=()=>{let it=libraryItem(st.sel);if(!saved(st.sel))add(st.sel);updateLib(it.key,'notes',$('modalNotes').value)};if($('modalProgress'))$('modalProgress').oninput=()=>{let it=libraryItem(st.sel);if(!saved(st.sel))add(st.sel,'A ler');updateLib(it.key,'progress',+$('modalProgress').value)};if($('addQuote'))$('addQuote').onclick=()=>{let q=$('newQuote').value.trim();if(!q)return;let it=libraryItem(st.sel);if(!saved(st.sel))add(st.sel);it=st.lib.find(x=>x.key===it.key);it.quotes=it.quotes||[];it.quotes.push(q);persist();render()};document.querySelectorAll('[data-del-quote]').forEach(b=>b.onclick=()=>{let it=st.lib.find(x=>x.key===key(st.sel));if(it){it.quotes.splice(+b.dataset.delQuote,1);persist();render()}})}
render();
})();